module.exports = {
    emailTemplate: "<div>Dear {{name}}</div><div><br /></div><div>We are delighted to inform you that your account for {{society_name}} has been successfully created on the Central Registrar for Cooperative Societies (CRCS) platform. You can now log in and start the application process to get your society approved and registered.</div><div><br /></div><div>To access your account, please visit the CRCS website.</div><div><br /></div><div>Once logged in, you will be able to fill out the application form for society registration. Our platform provides a streamlined process to ensure a smooth experience for you.</div><div><br /></div><div>If you have any questions or need assistance during the application process, please don't hesitate to reach out to our support team. We are here to help you at every step of the way.</div><div><br /></div><div>Thank you for choosing CRCS for your society registration needs. We look forward to serving you.</div><div><br /></div><div>Best regards,</div><div>Central Registrar for Cooperative Societies</div>",

    approveEmailTemplate: "<div>Dear {{name}},</div><div><br /></div><div>We are pleased to inform you that your application for {{reason}} has been approved by the Central Registrar for Cooperative Societies (CRCS).</div><div><br /></div><div>As a result of the approval, you can now proceed to download the certificate for your application from the CRCS platform. The certificate serves as official documentation of your approved application.</div><div><br /></div><div>To access the certificate, please follow these steps:</div><div><br /></div><div>1. Visit the CRCS website.</div><div>2. Log in to your account using your credentials.</div><div>3. Navigate to the 'My Applications' section.</div><div>4. Locate your approved application for {{reason}}.</div><div>5. Click on the 'Download Certificate' button next to the application.</div><div><br /></div><div>By downloading the certificate, you will have a tangible proof of the successful approval of your application. This certificate holds great value and can be used for official purposes related to your cooperative society.</div><div><br /></div><div>If you have any questions or require further assistance regarding the certificate or any other matter, please feel free to reach out to our support team. We are here to help you.</div><div><br /></div><div>Best regards,</div><div>Central Registrar for Cooperative Societies</div>",

    declineEmailTemplate: "<div>Dear {{name}},</div><div><br /></div><div>We hope this email finds you well. We wanted to inform you about an update regarding your application-{{id}} for {{reason}} submitted to the Central Registry of Cooperative Societies.</div><div><br /></div><div>After careful review and consideration, we regret to inform you that your application has been declined by the CRCS. However, we have uploaded the order and notices, please have a look at them and make necessary changes in your application.</div><div><br /></div><div>Please log in to your account on the CRCS platform to access the updated information. Once logged in, you will find the updated order and notices related to your application. These documents highlight the specific areas that need attention and modification.</div><div><br /></div><div>If you have any questions or require further assistance, please do not hesitate to reach out to our support team. We are here to help you throughout the process.</div><div><br /></div><div><br /></div><div>Best regards,</div><div>Central Registry of Cooperative Societies.</div>",

    resetPasswordEmailTemplate: "<p>Hello {{name}},</p><p><br /></p><p>This is a confirmation email to verify your request for a password reset. Please use the following OTP to proceed with the password change:</p><p><br /></p><p>OTP: {{otp}}</p><p><br /></p><p>Please enter the OTP in the provided field on the password reset page. Please note that this OTP is valid for 5 minutes only.</p><p><br /></p><p>If you did not initiate the password reset, please ignore this email.</p><p><br /></p><p>Thank you.</p><p><br /></p><p>Best regards,</p><p>Central Registry of Cooperative Societies</p>"
}

